-- create table  if not exists user  (
--     id          identity        not null,
--     first_name  varchar(255)    not null,
--     last_name   varchar(255)    not null,
--     email       varchar(255)    not null,
--     password    varchar(255)    not null
-- )
CREATE TABLE IF NOT EXISTS user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL
    );
